name: pytorch14
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - backcall=0.1.0=py_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py38_0
  - configargparse=1.0=py_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cython=0.29.15=py38he1b5a44_0
  - decorator=4.4.1=py_0
  - dill=0.3.1.1=py38_0
  - freetype=2.10.0=he983fc9_1
  - intel-openmp=2020.0=166
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py38_0
  - jpeg=9c=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - lz4-c=1.8.3=he1b5a44_1001
  - mkl=2020.0=166
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.10.0=hc9558a2_0
  - nltk=3.4.4=py_0
  - numpy=1.18.1=py38h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=h516909a_0
  - parso=0.6.1=py_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.0.0=py38hefe7db6_0
  - pip=20.0.2=py_2
  - prompt_toolkit=3.0.3=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.5.2=py_0
  - python=3.8.1=h357f687_2
  - pytorch=1.4.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pyyaml=5.3=py38h516909a_0
  - readline=8.0=hf8c457e_0
  - scipy=1.4.1=py38h921218d_0
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.5.0=py38_cu101
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.8=py_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.2.2=h516909a_1
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - absl-py==0.9.0
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==7.1.1
    - flask==1.1.1
    - future==0.18.2
    - google-auth==1.11.3
    - google-auth-oauthlib==0.4.1
    - grpcio==1.28.0rc3
    - idna==2.8
    - itsdangerous==1.1.0
    - jinja2==3.0.0a1
    - kenlm==0.0.0
    - markdown==3.2.1
    - markupsafe==1.1.1
    - oauthlib==3.1.0
    - opennmt-py==1.1.1
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyonmttok==1.18.3
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - sentencepiece==0.1.85
    - tensorboard==2.1.1
    - torchtext==0.4.0
    - tqdm==4.30.0
    - urllib3==1.25.8
    - waitress==1.4.3
    - werkzeug==1.0.0
    - wheel==0.34.2
prefix: /home/cruys/anaconda3/envs/pytorch14

